version: '3.4'

services:
  redtest.topup.api:
    image: redtesttopupapi
    build:
      context: .
      dockerfile: RedTest.TopUp.API/Dockerfile
    depends_on:
    - db
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - pgdata:/var/lib/postgresql/red_datapostgres

volumes:
  pgdata: